#!/bin/bash

uptime=$(</proc/uptime)
uptime=${uptime%%.*}

s=$(( uptime%60 ))
m=$(( uptime/60%60 ))
h=$(( uptime/60/60%24 ))
d=$(( uptime/60/60/24 ))

echo ""$(printf %02d $h)":"$(printf %02d $h)":"$(printf %02d $m)
